#
# build libSBTL_CarbonDioxide using libMesh's build system
#
LIBSBTL_CARBON_DIOXIDE_DIR       := $(CARBON_DIOXIDE_DIR)/contrib/libSBTL_CarbonDioxide

LIBSBTL_CARBON_DIOXIDE_srcfiles  :=
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/CP_VU_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/CP_VU_L_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/CV_VU_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/CV_VU_L_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/ETA_VU_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/ETA_VU_L_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/G_VU_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/G_VU_L_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/H_S_TMAX_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/H_S_UC_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/H_S_UC_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/H_V_TMAX_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/H_V_UC_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/H1_P_SPL_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/H2_S_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/H2_V_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/HS_FLASH_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/LAMBDA_VU_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/LAMBDA_VU_L_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/LibSBTL_vu_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/P_VU_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/P_VU_L_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PH_FLASH_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PS_FLASH_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PS_H_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PS_S_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PS_SH_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PS_T_INV_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PS_U_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PS_V_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PS_VH_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PS_VU_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/PT_FLASH_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/S_H_PMAX_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/S_H_PMAX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/S_H_PMIN_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/S_VU_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/S_VU_L_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/S1_H_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/S1_H_SPL_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/S1_P_SPL_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/SAT_VU_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/SIGMA_TS_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/T_P_UC_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/T_VU_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/T_VU_L_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/TS_P_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/U_V_TMAX_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/U_VH_G_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/U_VH_L_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/U_VP_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/U_VP_L_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/U_VP_L_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/U1_T_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/U2_T_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/U2_V_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V_H_PMAX_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V_H_PMAX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V_H_PMIN_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V_P_UC_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V_U_PMAX_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V_U_PMAX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V1_H_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V1_H_SPL_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V1_T_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V1_U_SPL_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/V2_P_AUX_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/VH_FLASH_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/VU_HP_G_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/VU_HP_L_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/VU_SH_G_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/VU_SH_L_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/VU_SP_G_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/VU_SP_L_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/VU_TP_G_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/VU_TP_L_INI_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/W_VU_G_CO2.cpp
LIBSBTL_CARBON_DIOXIDE_srcfiles  += $(LIBSBTL_CARBON_DIOXIDE_DIR)/W_VU_L_CO2.cpp


# add the following flags to calculate the heat capacities, cp and cv, as well as the free enthalpy, g, from auxiliary spline functions
# otherwise (default):
#   cp and cv are calculated from the derivatives of p(v,u) and t(v,u) - derivatives of cp and cv show some smaller discontinuities
#   g is calculated from g=u+p*v-t*s - calculation of g is approx. 3 times slower with regard to g(v,u) from the auxiliary spline
# ADDITIONAL_CPPFLAGS += -DSBTL_USE_C_AUX
# ADDITIONAL_CPPFLAGS += -DSBTL_USE_G_AUX

LIBSBTL_CARBON_DIOXIDE_objects   := $(patsubst %.cpp, %.$(obj-suffix), $(LIBSBTL_CARBON_DIOXIDE_srcfiles))
LIBSBTL_CARBON_DIOXIDE_deps      := $(patsubst %.$(obj-suffix), %.$(obj-suffix).d, $(LIBSBTL_CARBON_DIOXIDE_objects))
LIBSBTL_CARBON_DIOXIDE_LIB       := $(LIBSBTL_CARBON_DIOXIDE_DIR)/libSBTL_CarbonDioxide-$(METHOD).la

app_INCLUDES += -I$(CARBON_DIOXIDE_DIR)
app_LIBS += $(LIBSBTL_CARBON_DIOXIDE_LIB)

$(LIBSBTL_CARBON_DIOXIDE_LIB): $(LIBSBTL_CARBON_DIOXIDE_objects)
	@echo "Linking Library "$@"..."
	@$(libmesh_LIBTOOL) --tag=CC $(LIBTOOLFLAGS) --mode=link --quiet \
	  $(libmesh_CC) $(libmesh_CFLAGS) -o $@ $(LIBSBTL_CARBON_DIOXIDE_objects) $(libmesh_LDFLAGS) $(EXTERNAL_FLAGS) -rpath $(LIBSBTL_CARBON_DIOXIDE_DIR)
	@$(libmesh_LIBTOOL) --mode=install --quiet install -c $(LIBSBTL_CARBON_DIOXIDE_LIB) $(LIBSBTL_CARBON_DIOXIDE_DIR)

$(app_EXEC): $(LIBSBTL_CARBON_DIOXIDE_LIB)

-include $(LIBSBTL_CARBON_DIOXIDE_deps)

cleanlibSBTL_CarbonDioxide:
	@echo "Cleaning libSBTL_CarbonDioxide"
	@rm -f $(LIBSBTL_CARBON_DIOXIDE_objects)
	@rm -f $(LIBSBTL_CARBON_DIOXIDE_deps)
	@rm -f $(LIBSBTL_CARBON_DIOXIDE_LIB)
	@rm -f $(LIBSBTL_CARBON_DIOXIDE_DIR)/libSBTL_CarbonDioxide-$(METHOD)*.dylib
	@rm -f $(LIBSBTL_CARBON_DIOXIDE_DIR)/libSBTL_CarbonDioxide-$(METHOD)*.so*
	@rm -f $(LIBSBTL_CARBON_DIOXIDE_DIR)/libSBTL_CarbonDioxide-$(METHOD)*.a
